[project]
name = "strledger"
version = "0.11.0"
description = "Ledger Hardware Wallet Stellar Python bindings."
authors = [{ name = "overcat", email = "4catcode@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
keywords = ["stellar", "ledger"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
dependencies = [
    "click>=8.5.0",
    "stellar-sdk>=16.1.0",
    "ledgerwallet>=0.10.0",
]

[project.urls]
Homepage = "https://github.com/lightsail-network/strledger"
Repository = "https://github.com/lightsail-network/strledger"
Documentation = "https://github.com/lightsail-network/strledger"
"Bug Tracker" = "https://github.com/lightsail-network/strledger/issues"

[project.scripts]
strledger = "strledger.cli:cli"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
